const githubConstants = {
    OPEN_ISSUES_FETCH_REQUEST: 'OPEN_ISSUES_FETCH_REQUEST',
    OPEN_ISSUES_FETCH_SUCCESS: 'OPEN_ISSUES_FETCH_SUCCESS',
    OPEN_ISSUES_FETCH_FAILURE: 'OPEN_ISSUES_FETCH_FAILURE',
}
export default githubConstants;

